#  Assignment 5: Reproducability

## Notebook made by  

|** Name** | **Student id** | **email**|
|:- |:-|:-|
|. | | |
|  | |. |

### Pledge (taken from [Coursera's Honor Code](https://www.coursera.org/about/terms/honorcode) )



Put here a selfie with your photo where you hold a signed paper with the following text: (if this is team work, put two selfies here). The link must be to some place on the web, not to a local file. 

> My answers to homework, quizzes and exams will be my own work (except for assignments that explicitly permit collaboration).

>I will not make solutions to homework, quizzes or exams available to anyone else. This includes both solutions written by me, as well as any official solutions provided by the course staff.

>I will not engage in any other activities that will dishonestly improve my results or dishonestly improve/hurt the results of others.

<img src='link to your selfie'/>

### Note
* **Assignments without the selfies or completely filled in information will not be graded and receive 0 points.**

  We bekijken   het artikel <http://language.media.mit.edu/paper> en zien in hoeverre we uit de ruwe data dezelfde gegevens kunnen halen als de auteurs van het artikel. Eerst maken  we de netwerkdata gebaseerd op boekvertalingen.

Daarna  gaan we de netwerkdata gebaseerd op de wikipedia data maken. De ruwe wikipedia "tsv" (voor tab separated) lijkt wel een spreadsheet, maar is in een onhandig formaat omdat de regels geen vast aantal kolommen hebben. We zullen dat eerst handmatig moeten oplossen.

In [3]:
%matplotlib inline
import pandas as pd
import re
from lxml import etree 
from bz2file import BZ2File
import codecs
import nltk
from collections import defaultdict
from  itertools import combinations  # ideal for creating all possible pairs that one can make out of a set
from __future__ import division
from math import sqrt

# Deel boekvertalingen

# 1

Read the spreadsheet on `http://language.media.mit.edu/data/public/unesco_langlang_20120722_iso639-3.txt` directly in in pandas in a dataframe called `raw`, and show the first 5 lines of the dataframe `raw`.

* this must be done in 2 lines

# 2 
We zijn natuurlijk in de Nederlandse taal geinterreseerd. Die heeft code `nld`.

1. Hoeveel regels zijn er in `raw` met `nld` in de kolom `original_language`
2. En hoeveel in de kolom `target_language`
3. Naar welke taal zijn er de meeste vertalingen vanuit het Nederlands?  Geef een one liner die de top 5 laat zien. Je laat alleen de kolommen `['target_language','num_translations']` zien, en eventueel de index kolom.
4. Maak een plotje met op de x-as de namen van talen omgekeerd geordend op het aantal vertalingen, en op de y-as hoe veel vertalingen er vanuit het Nederlands naar die taal is. Zorg dat de y-as in een log schaal geplot wordt.  
    * Je krijgt een wiebelige bijna rechte dalende curve. De x-as  begint met `deu`.

# 3 

Bekijk eens de output van `spannend= raw.original_language.value_counts()`. Gebruik `?` om uit te vogelen wat `value_counts` eigenlijk doet.

1. Beschrijf, gebruikmakend van terminologie uit de theorie van sociale netwerken, wat `spannend` betekent.
2. Wat betekent `raw.target_language.value_counts()` dan?
3. Maak een pandas Series object genaamd `total_translations` (een Dataframe met maar 1 kolom) met de taalcode als index en met voor elke taal het totaal aantal vertalingen vanuit die taal als waarde. Sorteer weer omgekeerd. De top 5 ziet er dan als volgt uit:
```
eng    1225237
fra     216624
deu     201718
rus     101395
ita      66453
```
    1. Plot `total_translations` in loglog schaal. 
    2. Wat is de waarde in `total_translations` voor het Nederlands?

# 4

1. Geef de mediaan en het gemiddelde van het aantal vertalingen.
2. Hoeveel taal-paren hebben meer vertalingen dan de mediaan?

# Deel  Wikipedia  

 

1. Maak   van de Wikipedia _raw_ dataset de netwerk  datasets die op <http://language.media.mit.edu/data> beschreven staan. 
2. We bekijken in hoeverre onze resultaten afwijken van die in de geleverde bewerkte datasets.
3. We leggen eventuele verschillen uit.

#### In Stapjes

We doen de opdracht in een aantal stapjes.

#### Let op, je notebook moet vanzelf draaien. Alle data moet opgehaald worden.

# Download 

1. Download de ruwe dataset als zip file, ontzip hem en sla hem in de directory op waarin dit notebook ook staat.
    * Dit mag je met de hand doen. De code **moet niet runbaar** in je notebook staan.
    * Maar zorg dat de rest van de code er vanuit gaat dat `wikipedia_userlang_iso639-3.tsv` in dezelfde folder staat als dit notebook
2. Lees de 2 bewerkte datasets over Wikipedia _Wikipedia Stats by Language_ en _Edges_ direct in van de urls in  pandas Dataframes, die je respectivelijk `dataset_stats_wikipedia` en `wikipedia_edges` noemt.
    1. Maak de Taal code de index in het eerste frame, en hou alleen de Kolommen `['Editors', 'Edits','Multilinguals','Edits by mulitlinguals']`
    2. Sorteer het frame op de index
    2. Verwijder de kolommen `SourceLanguageName	TargetLanguageName	SourcePopulation	TargetPopulations` uit het tweede frame
    3. Sorteer het frame op `SourceLanguageName`
    3. Laat steeds met `head()` zien dat het werkt.
    
### Je antwoord bestaat uit 2 cellen

In [4]:
# jouw code hier 
dataset_stats_wikipedia = pd.read_csv('http://language.media.mit.edu/data/public/dataset_stats_wikipedia.tsv',delimiter='\t',encoding='utf-8',index_col='Language')
dataset_stats_wikipedia = dataset_stats_wikipedia[['Editors', 'Edits','Multilinguals','Edits by mulitlinguals']]
dataset_stats_wikipedia.sort_index()
dataset_stats_wikipedia.head()

           Editors   Edits  Multilinguals  Edits by mulitlinguals
Language
Abkhazian       15    2807              7                    1494
Afar             4      46              3                       9
Afrikaans      511  103652            352                   95988
Akan            31     327             24                     240
Albanian      1996  196685           1083                  137800

In [5]:
# jouw code hier  (verwijderen van de kolommen)
wikipedia_edges = pd.read_csv('http://language.media.mit.edu/data/public/wikipedia_edges.tsv',delimiter='\t',encoding='latin-1')
wikipedia_edges = wikipedia_edges.drop(['SourceLanguageName', 'TargetLanguageName', 'SourcePopulation', 'TargetPopulations'], axis=1)
wikipedia_edges.head()

,SourceLanguageCode,TargetLanguageCode,Coocurrences,PhiCorrelation,Tstatistic
0,afr,eng,271,0.013648,17.207148
1,afr,nld,78,0.015377,3.332197
2,amh,eng,28,0.004344,5.476711
3,ang,eng,51,0.006363,8.021067
4,ara,deu,446,0.007497,3.550224

In [6]:
# jouw code hier  (sorten op SourceLanguageName)
wikipedia_edges = pd.read_csv('http://language.media.mit.edu/data/public/wikipedia_edges.tsv',delimiter='\t',encoding='latin-1')
wikipedia_edges.sort_values(by=['SourceLanguageName'])
wikipedia_edges.head()

,SourceLanguageCode,TargetLanguageCode,SourceLanguageName,TargetLanguageName,SourcePopulation,TargetPopulations,Coocurrences,PhiCorrelation,Tstatistic
0,afr,eng,Afrikaans,English,776,273987,271,0.013648,17.207148
1,afr,nld,Afrikaans,Dutch,776,26888,78,0.015377,3.332197
2,amh,eng,Amharic,English,81,273987,28,0.004344,5.476711
3,ang,eng,Old English (ca. 450-1100),English,135,273987,51,0.006363,8.021067
4,ara,deu,Arabic,German,6361,103768,446,0.007497,3.550224

# Haal gegevens uit de ruwe data, deel 1

* De file `'wikipedia_userlang_iso639-3.tsv'` lijkt een spreadsheet maar hij heeft niet op elke regel evenveel kolommen.
* Processing met pandas is dus ook lastig.
* Als alternatief gaan we file zelf regel voor regel  inlezen, en de gewenste gegevens opslaan.
* Ons einddoel is om een dataframe te maken dat er precies zo uitziet als `dataset_stats_wikipedia`
* We doen dat in 2 stappen:
    1. We maken een aantal dicts aan met de gewenste gegevens
    2. Van elke dict maken we een dataframe met `pd.DataFrame.from_dict`
    3. Die plakken we allemaal aan elkaar met `join` (neem een inner join)
    4. Noem het eindresultaat `stats`, sorteer het ook op de index en laat het begin zien met `head`.
    5. Check natuurlijk zelf of je op de goede weg zit door je resultaat te vergelijken met `dataset_stats_wikipedia`
* Hieronder staat wat code om je op weg te helpen
* **Lees het artikel en de supplementary material goed om net als zij de ruwe data te filteren.**


# Haal gegevens uit de ruwe data, deel 2

* In dezelfde code waarin je de vorige vraag hebt gemaakt, maak je ook een dict `pairs` aan. Hier zijn de sleutels paren van taalcodes, **waarbij de eerste altijd alfabetisch eerder is dan de tweede**, en hun waarde het aantal cooccurences.
* Maak van dit dict een Dataframe `edges`, waarbij `edges.columns=['SourceLanguageCode','TargetLanguageCode','Coocurrencesmy']`
* Sorteer ook hier op `'SourceLanguageCode'`
* **Lees het artikel en de supplementary material goed om net als zij de ruwe data te filteren.**

In [8]:
# Your code 
with open('wikipedia_userlang_iso639-3.tsv', encoding='latin-1') as f:
    c=0
    editors=defaultdict(int)
    edits=defaultdict(int)
    multilingual=defaultdict(int)
    Edits_by_mulitlinguals=defaultdict(int)
    pairs= defaultdict(int)
    c=0
    for l in f:
        if c <100:
            print (l)
        # your code
        c+=1
        if c% 10**5==0:  # om te debuggen doe ik hier 10**2==0: break 
            print (c)
        
len(pairs)

! ! ! ! ! ! ! ! ! ! ! ! ! ! !	zho,7

! ! ! ! ! ! ! ! ! ! ! ! ! !	zho,8

! ! ! ! ! ! ! ! ! ! ! ! !	zho,30

! ! ! ! ! ! ! ! ! ! ! !	zho,7

! ! ! ! ! ! ! ! ! ! !	zho,5

! ! ! albertzuro	deu,1

! !!	eng,1

! ..dr.guevara.. !	ara,1	eng,1

! 0lm	deu,252

! 8 jojo 8 !	deu,2

! aaÄa !	tur,31

! ari-ari-ari !	jpn,7

! biswas amitava !	eng,11

! danskammelsrod !	spa,9

! eini	deu,2

! god	cos,1	chv,1	vie,1	deu,1	sqi,1	wln,1	arg,1	rus,15	lav,1

! jay !	eng,3

! kaiser	sqi,5

! lash.rubberea.com	arc,1

! rbrider !	ces,1

! shz	pol,1

! the black spot !	eng,4

! tre e mezzo !	ita,1

!! 'virgo rick' !!	eng,1

!! db	eng,6

!!! professional analism account! attaaaaaaaack!!!!	eng,2

!!!!! lesen !!!!!!	deu,5

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!ola sexy boyz	eng,1

!!!!!!!!!!!!!!!!!!!cammellobello	ita,10

!!!!!!!!!!!!!!!	deu,2

!!!!!adeen!!!!!	fin,365

!!!!akamcia	pol,111

!!!!miske	fin,2

!!!!wikipedia is girls aloud free web hosting!!!	eng,4

!!!(myestery dungeon)!!!	eng,1

!!!alert!!!	ces,13

!!!desperados!!!	deu,5

!!!dr.gaio!!!	ita,10

!!!dsavd	jpn,2

!!!esdv	jpn,1

!!!kjxfvyp	jpn,3

!!!lolersk8!!!	eng,7

!!!niloivenutfotuo	eng,1

!!!please block this account. thank you	eng,2

!!!rompeolas112!!!	spa,1

!!!ruddingstone!!!	eng,1

!!!s-tep-ha-n.cas!!!	deu,3

!!!scottishrabbit!!!	eng,3

!!!sr!!!	eng,2

!!!whus!!!	ita,60

!!!	jpn,82

!!!××××××!!!	heb,6

!!..:)	eng,1

!!2011worldprotest!extra account	eng,1

!!2011worldprotests!!appletart!!	eng,2

!!2011worldprotests!!	eng,49

!!8uyvasdaw	eng,8

!!@!!	eng,2

!!aaapplesauce	eng,3

!!aaardyvark!!	eng,1

!!aabgh!!	eng,1

!!archie!!	eng,89

!!conway-band!!	eng,1

!!cpluvsds!!	eng,3

!!cyber pinasco!!	ita,1

!!ee	jpn,1

!!gnikmra	eng,10

!!house down!!	eng,70

!!isheetoneggs!!	eng,1

!!linfon!!	eng,2

!!lokastory	fra,9

!!mese!!	fin,9

!!onpu	jpn,11

!!rozz!!	spa,1

!!samba2006!!	eng,2

!!sgott	eng,28

!!suzzy!!	tur,602

!!vennin!!	eng,4

!!viewcountfun1	eng,145

!!wawawiwa!!	eng,37

!!weed!!	jpn,12

!!wrewe	jpn,5

!!yeahman!!	deu,6

!!yoshiryu!!	jpn,1

!!	jpn,3	eng,1448

!!æ­»ã­	ara,3

!&quot;0000000000o00a	eng,1

!&quot;mr.brightsides&quot;!	spa,1

!&quot;Â£$%^&amp;*() +	eng,1

!&quot;Â£$	eng,8

!&quot;Â·$%&amp;	spa,2

!)ark machine	eng,1

!*!jodie-2007!*!	eng,5

!*peter*!	eng,3

!-!--:annekelol:--!-!	nld,1

!-!z3ta!-!	spa,11

!---slappdash---!	eng,128

!--mk--!	fra,8

!-artmaster	rus,2	ukr,216

!-boingbag-!	eng,3

100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
1800000
1900000
2000000
2100000
2200000
2300000
2400000
2500000
2600000
2700000
2800000
2900000
3000000
3100000
3200000
3300000
3400000
3500000
3600000
3700000
3800000
3900000
4000000
4100000
4200000
4300000
4400000
4500000
4600000
4700000
4800000
4900000
5000000
5100000
5200000
5300000
5400000
5500000
5600000
5700000
5800000
5900000
6000000
6100000
6200000
6300000
6400000
6500000
6600000
6700000
6800000
6900000
7000000
7100000
7200000
7300000

0

In [ ]:
#Deel 1
# jouw code hier 
stats.head()

In [ ]:
#Deel2

# jouw code hier 
edges.head(10)

# Vergelijk 

We gaan nu onze dataframes vergelijken met die we hebben opgehaald.

We zijn natuurlijk erg benieuwd of er verschillen zijn, en vooral ook groot die dan zijn, als ze er zijn.

1. Join `dataset_stats_wikipedia` en `stats` in een nieuwe dataframe `samen`. 
    * laat met `samen.describe()` zien hoe groot of klein de verschillen zijn
2. Maak een functie `fout_percentage` waar je twee kolommen en een dataframe aan geeft en die _het verschil tussen die twee kolommen bepaalt, en omzet naar een "foutpercentage"_.
3. Bereken dat percentage voor de vier kolommen `['Editors', 'Edits','Multilinguals','Edits by mulitlinguals']` en print het netjes uit.
4. Leg in een paar zinnen uit waarom jouw maat voor "foutpercentage" echt ergens op slaat, en het een goede indicator geeft. 
5. Doe tenslotte hetzelfde voor `edges`. 
    * Hier doe je natuurlijk een `merge`
    * Bekijk hier eens het verschil tussen een outer en een inner join.
    * Leg uit wat er hier aan de hand is.
    * Kan je het verschil verklaren?

In [ ]:
# vergelijk stats met dataset_stats_wikipedia

samen=

def fout_percentage(col1,col2,df):
     # jouw code hier 

 

for col in stats.columns:
    print ("%s\t%s\t%s" %(col, fout_percentage(col, col+'my', samen))

In [ ]:
samen.describe()

In [ ]:
# vergelijk edges met "inner join"

In [ ]:
# vergelijk edges met "outer join"

edges2=pd.merge(edges,wikipedia_edges, how='outer', on=['SourceLanguageCode','TargetLanguageCode'])
print (fout_percentage('Coocurrencesmy','Coocurrences', edges2))
edges2.describe()

# Reflectie
Je hebt getracht een deel van het artikel te reproduceren. Ook hebben we gedacht over het artikel en de mate van herhaalbaarheid van de vermelde gegevens. 

Geef nu in een half A4 je eigen mening. Behandel deze twee punten:

1. Wat was al goed gedaan?
2. Wat kon beter en hoe dan?